config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'
  resources :items do
    collection do
      get 'buy'
      get 'search'
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end
  resources :items do
    member do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end
  resources :users, only: :show

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  resources :purchase, only: [:show] do
    collection do
      post '/pay/:id', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :owners_area
  belongs_to_active_hash :status
  belongs_to_active_hash :shipping_fee
  belongs_to_active_hash :shipping_method
  belongs_to_active_hash :arrival_date

  belongs_to :user
  # belongs_to :category
  # category関係が終わった際に追加 永井
  
  # 不足っぽい
  validates :name,                presence: true
  validates :price,               presence: true
  validates :status_id,           presence: true
  validates :shipping_fee_id,     presence: true
  validates :shipping_method_id,  presence: true
  validates :owners_area_id,      presence: true
  validates :arrival_date_id,     presence: true
  validates :explain,             presence: true
  validates :a_category_id,       presence: true


  validates :price,              numericality: { only_integer: true,
                                                 greater_than_or_equal_to: 300,
                                                 less_than: 10000000}
  validates :status_id,          numericality: { only_integer: true,
                                                 greater_than_or_equal_to: 1,
                                                 less_than: 7}
  validates :shipping_fee_id,    numericality: { only_integer: true,
                                                 greater_than_or_equal_to: 1,
                                                 less_than: 3}
  validates :shipping_method_id, numericality: { only_integer: true,
                                                 greater_than_or_equal_to: 1,
                                                 less_than: 9}
  validates :owners_area_id,     numericality: { only_integer: true,
                                                 greater_than_or_equal_to: 1,
                                                 less_than: 48}
  validates :arrival_date_id,    numericality: { only_integer: true,
                                                  greater_than_or_equal_to: 1,
                                                  less_than: 4}


  # dependentで商品削除時に画像も削除
  has_many :item_images, dependent: :destroy


  # item削除時にimageも削除される
  accepts_nested_attributes_for :item_images, allow_destroy: true  
  validates :item_images,       presence: true

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]
  before_action :request_path

  # 商品詳細ページ (田村)
  def show
  end

  # トップページ・商品一覧ページ(本間・林)
  def index
    @items = Item.includes(:item_images).limit(3).order('created_at DESC')
    # itemに紐づいているitem_imagesを取得するためにincludesを使用
    # limit(3)でデータを３つまでしか表示できないように設定
    # order('created_at DESC')を使用することで、新しく出品された順に表示されるよう設定
  end

  # 商品出品ページ
  def new

    if user_signed_in?
      @item = Item.new(flash[:item])
      @item.item_images.new
      @category_parent = Category.roots
      
    else
      flash[:notice] = "商品の出品にはユーザー登録、もしくはログインをしてください"
      redirect_to new_user_registration_path
    end
  end

  def category_children
    @category_children = Category.find(params[:parent_id]).children
  end

  def category_grandchildren
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  # 商品出品機能
  # createしてしまうよりも、newでsaveすれば、true・false判定ができる
  def create
    @item = Item.new(item_params)
 
    if @item.save
      flash[:notice] = "
      「#{@item.name}」を出品しました"
      # データの作成時点で、@itemにIDをが付与されている
      redirect_to @item
    else
      # render :new   この記述だと2回送信しないとエラー表示が出ない
      redirect_to new_item_path
      flash[:notice] = @item.errors.full_messages
      # 再入力時に前回のデータを記憶 (#newのflashで受け取り)
      flash[:item] = @item
      flash[:notice] = @item.errors.full_messages

      if params[:parent_id] !=""
        @parentId = params[:parent_id]
        @category_children = Category.find(params[:parent_id]).children
        unless params[:children_id] ==""
          unless params[:children_id] =="---"
            @childrenId = params[:children_id]
            @category_grandchildren = Category.find(params[:children_id]).children
            @grandchildrenId = params[:item][:category_id]
          end
        end
      end

      # 上方でredirect_to new_item_pathが呼び出されているのでおそらく不要。エラー出る(田村)
      # render :new
    end
  end

  # 商品情報更新ページ (田村)
  def edit
    # @imgs[]

    # @item = current_user.items.find(params[:id])

    # @imgs.map { |img| img.image.cache! } unless @imgs.blank?
    # binding.pry
    @category_parent = Category.roots
    
    if user_signed_in? && current_user.id != @item.user_id
      redirect_to item_path
    end
  end

  # 商品情報更新機能 (田村)
  def update
    if @item.update(item_params)
      flash[:notice] = "
      「#{@item.name}」を編集しました"
      # データの作成時点で、@itemにIDをが付与されているから、@itemでも良さそう
      redirect_to item_path
    else
      redirect_to edit_item_path
      flash[:notice] = @item.errors.full_messages
      # if params[:parent_id] !=""
      #   @parentId = params[:parent_id]
      #   @category_children = Category.find(params[:parent_id]).children
      #   unless params[:children_id] ==""
      #     unless params[:children_id] =="---"
      #       @childrenId = params[:children_id]
      #       @category_grandchildren = Category.find(params[:children_id]).children
      #       @grandchildrenId = params[:item][:category_id]
      #     end
      #   end
      # end
      @parentId = params[:parent_id]
      @childrenId = params[:children_id]
      @grandchildrenId = params[:item][:category_id]
      @category_children = Category.find(params[:parent_id]).children
      @category_grandchildren = Category.find(params[:children_id]).children
    end
  end

  # 商品削除機能
  def destroy
    if user_signed_in? && current_user.id == @item.user_id
      flash[:notice] = "「#{@item.name}」を削除しました"
      @item.destroy
      redirect_to root_path
    else
      redirect_to item_path
    end
  end

  #商品購入機能（仮）
  def buy
  end

  #商品検索機能
  def search
    @items = Item.search(params[:keyword]).page(params[:page]).per(9)
  end

  private
  # 出品時にフォーム入力されるデータ
  def item_params
    params.require(:item).permit(:name, 
                                 :price, 
                                 :status_id, 
                                 :brand, 
                                 :shipping_fee_id, 
                                 :shipping_method_id, 
                                 :owners_area_id, 
                                 :arrival_date_id, 
                                 :explain, 
                                 :category_id, 
                                 :buyer_id,
                                 item_images_attributes: [:image, :_destroy, :id]
                                #  TODO: :idはもともと無かったけど必要か？
                                #  :image_cache
                                 ).merge(user_id: current_user.id)
  end

  def set_item
    # finb_byでないとエラーになる (nilを返さない)
    if Item.find_by_id(params[:id]).nil?
      flash[:notice] = "指定の商品は存在しません"
      redirect_to root_path
    else
      @item = Item.find(params[:id])
      @name = @item.name
      @price = @item.price
      @brand = @item.brand
      @explain = @item.explain

      # active_hashを利用
      @status = @item.status.name
      @shipping_fee = @item.shipping_fee.name
      @shipping_method = @item.shipping_method.name 
      @owners_area = @item.owners_area.name
      @arrival_date = @item.arrival_date.name

      # 仮
      @user = User.find(@item.user_id).nickname
      @buyer = @item.buyer_id

      # 配列なのでs付けておく
      @imgs = ItemImage.where(item_id: params[:id]) 
    end
  end

  # アクション毎にビューを条件分岐可能にする
  def request_path
      @path = controller_path + '#' + action_name
      def @path.is(*str)
          str.map{|s| self.include?(s)}.include?(true)
      end
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
.wrapper
  .input_area
    = form_for [@item] do |f|

      .image
        .image__top
          出品画像
          %span.image__top--red
            必須
        .image__text
          -# 最大10枚までアップロードできます。
        -# %label
        .image_form
          -# = icon('fas', 'camera', class: "image_form__item image_form__item--icon")
          -# .image_form__item
            -# ドラッグアンドドロップ
            -# ドラックアンドドロップについてはjquery時に作業するorクリック式のみのアップロードにしてドロップアンドドロップを消す
            -# クリックしてファイルをアップロード
            -# %br
            -# %br

            -# field_for 親モデルと子モデルを同時に保存・更新できる (1投稿に対して、複数の画像)
          = f.fields_for :item_images do |image|
            .js_file_group{data: {index: image.index}}
              = icon('fas', 'minus-circle', class: 'js-remove')
              = image.file_field :image, class: "js_file_group__display" 


        .imgBox
          -# アクション毎にビューの表示を条件分岐
          -if @path.is('items#new')
            new
          -if @path.is('items#edit')
            edit
            -# = f.hidden_field :img.image_cache
            -# %ul.main__imgs__list
            -#   -@imgs.each do |i|
            -#     %li.main__imgs__list__img
            -#       =image_tag i.image_url, class: ""

      .overview
        .name
          .name__top
            商品名
            %span.name__top--red
              必須
          = f.text_field :name, class: "name__form", placeholder: "40文字まで"
        .explain
          .explain__top
            商品の説明
            %span.name__top--red
              必須
          = f.text_area :explain, class: "explain__form", placeholder: "商品の説明 (1000文字まで)"
          .explain_bottom
            .explain_bottom__caracters_number
              0/1000
      .detail
        商品の詳細
        .category
          .category__top
            カテゴリー
            %span.category__top--red
              必須
          = f.fields_for :a_category do |d|
            = f.collection_select :a_category_id, ACategory.all, :id, :name, {prompt: "✔︎ 選択してください"}, {class: "category__form"}
          -# ここではactivehashを利用したデータ選択を行っています。category関係の作業が進んだ後、切替を行う。 永井
        .brand
          .brand__top
            ブランド
            %span.brand__top--gray
              任意
          = f.text_field :brand, class: "brand__form", placeholder: "例) シャネル"
        .status
          .status__top
            商品の状態
            %span.status__top--red
              必須
          = f.fields_for :status do |d|
            = f.collection_select :status_id, Status.all, :id, :name, {prompt: "✔︎ 選択してください"}, {class: "status__form"}
      .shipping_relation
        配送について
        .fee
          .fee__top
            配送料の負担
            %span.fee__top--red
              必須
          = f.fields_for :shipping_fee do |d|
            = f.collection_select :shipping_fee_id, ShippingFee.all, :id, :name, {prompt: "✔︎ 選択してください"}, {class: "fee__form"}
        .method
          .method__top
            配送方法
            %span.method__top--red
              必須
          = f.fields_for :shipping_method do |d|
            = f.collection_select :shipping_method_id, ShippingMethod.all, :id, :name, {prompt: "✔︎ 選択してください"}, {class: "method__form"}
        .owner_area
          .owner_area__top
            発送元の地域
            %span.owner_area__top--red
              必須
          = f.fields_for :oweners_area do |d|
            = f.collection_select :owners_area_id, OwnersArea.all, :id, :name, {prompt: "✔︎ 選択してください"}, {class: "owner_area__form"}
        .arrival_date
          .arrival_date__top
            発送までの日数
            %span.arrival_date__top--red
              必須
          = f.fields_for :arrival_date do |d|
            = f.collection_select :arrival_date_id, ArrivalDate.all, :id, :name, {prompt: "✔︎ 選択してください"}, {class: "arrival_date__form"}
      .price
        .price__limit
          価格（¥300~9,999,999）
        .price_input
          .price_input__top
            販売価格
            %span.price_input__top--red
              必須
          .price_input__form
            ¥
            = f.number_field :price, class: "price_input__form--number", placeholder: "0"
        .brokerge_fee
          .brokerge_fee__rate
            販売手数料（10％）
          .brokerge_fee__calculation
            ー
        .profit
          .profit__text
            販売利益
          .profit__calculation
            ー
      .submit
        = f.submit '送信する', class: "submit__btn"
        -# %input{type: "submit", value: "出品する", class: "submit__btn"}
      .link_top_page
        =link_to root_path, class: "link_top_page__text" do
          もどる
      .cautions_information
        禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

app/views/items/buy.html.haml
-# %body
-#   %header.header
.buy-wrap

  .buy-head
    = link_to "#", class:"header__link" do
      = image_tag asset_path('logo.png'), alt: 'アイコン',width: '180px', class: 'header__link__img'

  .buy-main
    .buy-main__head
      購入内容の確認
    .buy-main__item
      .buy-main__item__inner
        .item-box
          .item-box__img
            = image_tag asset_path("a007.png"), class: 'item-box__img'
          .item-box__details
            %p.item-box__details--name
              商品名：サンプル
            %p.item-box__details--price
              ¥800（税込）送料込み
    
    .buy-main__content
      .buy-main__content__inner
        %form.buy-form
          .buy-price-box
            .buy-price-box__title
              支払い金額
            .buy-price-box__price
              ¥800 
        
          .pay-method-box
            .pay-method-box__inner
              .pay-method-box__inner__top
                .pay-method-box__inner__top__left
                  支払い方法
                .pay-method-box__inner__top__right
                  = link_to "変更する", "#", class: "pay-method-box__inner__top__right--link"
              .pay-method-box__inner__text
                クレジットカード
                %br 
                ********1234
                %br
                有効期限 11/11
          
          .delivery-address-box
            .delivery-address-box__inner
              .delivery-address-box__inner__top
                .delivery-address-box__inner__top__left
                  配送先
                .delivery-address-box__inner__top__right
                  = link_to "変更する", "#"
              .delivery-address-box__inner__text
                〒111-1111
                %br
                東京都世田谷区〇〇1-1-1
                %br
                テックキャンプ 太郎
          
          .bottom-box
            %button.bottom-box__btn{type: "submit"} 購入する

    .buy-footer
      .buy-footer__nav
        %ul.buy-footer__nav__list
          %li.buy-footer__nav__list--text
            = link_to "会社概要（運営会社）"
          %li.buy-footer__nav__list--text
            = link_to "プライバシーポリシー"
          %li.buy-footer__nav__list--text
            = link_to "FURUMA 利用規約"
          
      .buy-footer__logo
        = link_to "#", class:"footer__logo__link" do
          = image_tag asset_path('logo-white.png'), alt: 'アイコン',width: '120px', class: 'footer__logo__link--img'
        .copy-right
          ©️FURUMA

        

app/views/items/edit.html.haml
=render "form"

app/views/items/index.html.haml
.index-container
  .intro
    .intro__content
      %h2.intro__content__subtitle
        人生を変えるフリマアプリ
      %p.intro__content__text
        FURIMAは誰にでも簡単に出品・購入できる
        %br
        フリマアプリです
      .intro__content__btn
        = link_to "#" do
          =image_tag asset_path("Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg"), class: "intro__content__btn--a-btn"
        = link_to "#" do
          =image_tag asset_path("google-play-badge.png"), class: "intro__content__btn--g-btn"
  
  .top-container
    %h2.top-container__title
      FURIMAが選ばれる３つの理由
    %ul.top-container__lists
      %li.list
        .list__image
          %span.list__image--number 1
          = image_tag asset_path("pict-reason-01.jpg"), class: 'list__image--img'

        %h3.list__text
          %span.list__text--strong 
            3分
          ですぐに出品
        %p.list__description
          スマホで入力するだけで簡単に出品できる

      %li.list
        .list__image
          %span.list__image--number 2
          = image_tag asset_path("pict-reason-02.jpg"), class: 'list__image--img'
        %h3.list__text
          %span.list__text--strong 
            シンプル
          で使いやすい
        %p.list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！

      %li.list.list__last
        .list__image
          %span.list__image--number 3
          = image_tag asset_path("pict-reason-03.jpg"), class: 'list__image--img'
        %h3.list__text
          手数料
          %span.list__text--strong 
            業界最安
        %p.list__description
          最大3％でお得に出品＆購入！

  .intro-middle
    .intro-middle__content
      %h2.intro-middle__content__subtitle
        会員数日本一
      %p.intro-middle__content__text
        FURIMAは、フリマアプリでも人気。
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .intro-middle__content__btn
        = link_to "#" do
          =image_tag asset_path("Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg"), class: "intro__content__btn--a-btn"
        = link_to "#" do
          =image_tag asset_path("google-play-badge.png"), class: "intro__content__btn--g-btn"

  .middle-container
    %h2.middle-container__title
      FURIMAの特徴
    %ul.middle-container__lists
      %li.list
        .list__image
          = image_tag asset_path("icon-01.png"), class: 'list__image--img'
        %h3.list__text
          簡単に売り買いできる
        %p.list__description
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能

      %li.list
        .list__image
          = image_tag asset_path("icon-03.png"), class: 'list__image--img'
        %h3.list__text
          売上金は即日振り込みに対応
        %p.list__description
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！

      %li.list.list__last
        .list__image
          = image_tag asset_path("icon-04.png"), class: 'list__image--img'
        %h3.list__text
          様々な支払いに対応
        %p.list__description
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  .category-pickup
    %h1.category-pickup__title
      ピックアップカテゴリー
    .category-pickup__box
      .category-pickup__box__head
        = link_to "#", class:"title" do
          %h3.title__text 新規投稿商品

      .category-pickup__lists-box
        - @items.each do |item|
          .category-lists
            =link_to item_path(item.id) do
              - if item.buyer_id?
                .sold-badge
              = image_tag item.item_images.first.image.url, class: 'lists__image--img'
              .category-lists__box
                %h3.category-lists__name
                  = item.name
                .category-lists__price-box
                  %ul.price
                    %li.price-list
                      = "#{item.price}円" 
                    %li.favorite
                      = icon('fas', 'star', class: 'icon_favorite')
                      0
                  %P.tax
                    (税込)


  .brand-pickup
    %h1.category-pickup__title
      ピックアップブランド
    .brand-pickup__box
      .brand-pickup__box__head
        =link_to "#",class:"title" do
          %h3.title__text アーカイバ
      .brand-pickup__lists-box
        .brand-lists
          =link_to "#",class:"list" do
            = image_tag asset_path("a007.png"), class: 'lists__image--img'
            .brand-lists__box
              %h3.brand-lists__name
                ゲゲゲのゲ
              .brand-lists__price-box
                %ul.price
                  %li.price-list
                    30000円
                  %li.favorite
                    = icon('fas', 'star', class: 'icon_favorite')
                    0
                %P.tax
                  (税込)
        .brand-lists
          =link_to "#",class:"list" do
            = image_tag asset_path("a001.png"), class: 'lists__image--img'
            .brand-lists__box
              %h3.category-lists__name
                カレーは飲み物
              .brand-lists__price-box
                %ul.price
                  %li.price-list
                    30000円
                  %li.favorite
                    = icon('fas', 'star', class: 'icon_favorite')
                    0
                %P.tax
                  (税込)
        .brand-lists
          =link_to "#",class:"list" do
            = image_tag asset_path("a004.png"), class: 'lists__image--img'
            .brand-lists__box
              %h3.brand-lists__name
                餃子の王将
              .brand-lists__price-box
                %ul.price
                  %li.price-list
                    30000円
                  %li.favorite
                    = icon('fas', 'star', class: 'icon_favorite')
                    0
                %P.tax
                  (税込)

  = link_to new_item_path do
    .purchace-btn
      .span.purchace-btn__text
        出品する
      = image_tag asset_path('icon_camera.png'), class: 'purchace-btn__img' 

app/views/items/new.html.haml
=render "form"

app/views/items/show.html.haml
.itemsShow
  %main.main
    .main__name
      =@name
    .main__imgs
      =image_tag @imgs[0].image_url, class: "main__imgs__img"

      %ul.main__imgs__list
        -@imgs.each do |i|
          %li.main__imgs__list__img
            =image_tag i.image_url, class: ""

    %p.main__price
      \\
      =@price
      %p.main__price__sub
        (税込) 送料込み
    

    
    -unless @buyer.nil?
      .main__buy__soldout
        売り切れ

    -else
      -if user_signed_in? && current_user.id == @item.user_id
        =link_to "商品の編集", edit_item_path, class:"main__edit"
        =link_to item_path, method: :delete, class:"main__destroy", data: { confirm: "削除してもよろしいですか？"} do
          商品の削除

      -if user_signed_in? && current_user.id != @item.user_id
        =link_to purchase_path(@item), class:"main__buy" do
          購入画面に進む


    %p.main__description
      =@explain

    %table.main__info
      %tbody
        %tr
          %th
            商品の状態
          %td
            =@status
        %tr
          %th
            ブランド
          %td
            %a
              =@brand
        %tr
          %th
            配送料の負担
          %td
            =@shipping_fee
        %tr
          %th
            配送方法
          %td
            =@shipping_method
        %tr
          %th
            発送元の地域
          %td
            =@owners_area
        %tr
          %th
            発送日の目安
          %td
            =@arrival_date
        %tr
          %th
            出品者
          %td
            =@user
        %tr
          %th
            カテゴリー
          %td
            %div
              = link_to @item.category.parent.parent.name
            %div 
              = link_to @item.category.parent.name
            %div
              = link_to @item.category.name

    .main__low
      %a.main__low--like
        \★ お気に入り 3
      %a.main__low--report
        =icon("fa", "flag")
        不適切な商品の通報

  %form.comment
    %textarea.comment__txt
    .comment__caution
      相手のことを考え丁寧なコメントを心がけましょう。<br>
      不快な言葉遣いなどは利用制限や退会処分となることがあります。
    %button.comment__btn
      =icon("fas", "comment")
      コメントする
  
  .more
    .preNextBox
      =link_to "< 前の商品", "#", class: "preBtn"
      =link_to "#", class: "nextBtn" do
        -# =params[:id].to_i - 1
        -# = "#{item_path}" + "#{params[:id].to_i - 1}"
        次の商品 >
    -# =link_to "#{Category.find(@item.category_id).name}をもっと見る", "#", class:"moreBtn"