config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'
  resources :items do
    collection do
      get 'buy'
      get 'search'
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end
  resources :items do
    member do
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end
  end
  resources :users, only: :show

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  resources :purchase, only: [:show] do
    collection do
      post '/pay/:id', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end
end

app/views/layouts/_footer.html.haml
.footer
  .up_area
    .inner
      .inner__title
        だれでもかんたん、人生を変えるフリマアプリ
      .inner__text
        今すぐ無料ダウンロード！
      .download_form
        = link_to "#" do
          =image_tag asset_path("Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg"), class: "download_form__icon download_form__icon--app_store"
        = link_to "#" do
          =image_tag asset_path("google-play-badge.png"), class: "download_form__icon download_form__icon--google_play"
  .low_area
    %ul.contents
      %li.low-content
        .low-content__title
          Fulimaについて
        %ul
          %li.list
            = link_to "#", class: "list__link" do
              会社概要(運営会社)
          %li.list
            = link_to "#", class: "list__link" do
              プライバシーポリシー
          %li.list
            = link_to "#", class: "list__link" do
              FURIMA利用規約
          %li.list
            = link_to "#", class: "list__link" do
              ポイントに関する特約
      %li.low-content
        .low-content__title
          Fulimaを見る
        %ul
          %li.list
            = link_to "#", class: "list__link" do
              カテゴリー一覧
          %li.list
            = link_to "#", class: "list__link" do
              ブランド一覧
      %li.low-content
        .low-content__title
          ヘルプ＆ガイド
        %ul
          %li.list
            = link_to "#", class: "list__link" do
              FURIMAガイド
          %li.list
            = link_to "#", class: "list__link" do
              FURIMAロゴ利用ガイドライン
          %li.list
            = link_to "#", class: "list__link" do
              お知らせ
    .footer_logo
      = link_to '#' do
        = image_tag asset_path("logo/logo-white.png"), class: "footer_logo__icon"
      .footer_logo__copyright
        ©︎ FURIMA

app/views/layouts/_header.html.haml
%header.head
  -if flash[:notice].instance_of?(Array)
    %ul.head__flash
      -flash[:notice].each do |notice|
        %li
          =notice
  -else
    %ul.head__flash
      %li
        =notice

  .head__in
    = form_with(url: search_items_path, local: true, method: :get) do |f|
      .head__in__up
        %h1
          =link_to root_path do
            =image_tag asset_path("logo/logo.png"),  class: "head__in__up__logo"
        .head__in__up__search
          = f.text_field :keyword, class: "head__in__up__search__txt", placeholder:"キーワードから探す"
          %label.head__in__up__search__btn
            = icon('fas', 'search', class: '')
            = f.submit "", class: "head__in__up__search__btn--display"
    .head__in__nav
      .head__in__nav__left
        .head__in__nav__left__cate
          カテゴリー
          %ul.category1
            - @category_parent.each do |parent|
              %li.parent__list
                = link_to parent.name
                %ul.category2
                  - parent.children.each do |child|
                    %li.child__list
                      =link_to child.name
                      %ul.category3
                        - child.children.each do |grandchild|
                          %li.grandchild__list
                            = link_to grandchild.name

        .head__in__nav__left__brand
          ブランド

      %ul.head__in__nav__right
        %li
          =link_to "商品1", "/items/1"
        %li
          =link_to "商品2", "/items/2"
        %li
          =link_to "商品3", "/items/3"
        %li
          =link_to "商品4", "/items/4"
        %li
          =link_to "商品5", "/items/5"


        -if user_signed_in?
          %li.head__in__nav__right__new
            =link_to "出品", new_item_path
          %li.head__in__nav__right__mypage
            =link_to "マイページ", user_path(current_user)
          %li.head__in__nav__right__mypage
            =link_to "カード情報変更", card_path(current_user)
          %li.head__in__nav__right__logout
            =link_to "ログアウト", destroy_user_session_path, method: :delete

        -else
          %li.head__in__nav__right__new
            =link_to "新規登録", new_user_registration_path
          %li.head__in__nav__right__login
            =link_to "ログイン", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample68c
    -# Pay.jpの公式のjavascriptを読み込ませられるようする為
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = render "layouts/header"
    = yield
    = render "layouts/footer"